services:
  mobile:
    build:
      context: .
      dockerfile: mobile/Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - ./mobile:/opt/mobile/app:delegated
      - ./mobile/package.json:/opt/mobile/package.json
      - ./mobile/package-lock.json:/opt/mobile/package-lock.json
      - notused:/opt/mobile/app/node_modules
    healthcheck:
      disable: true

volumes:
  notused:
